#
# ~/.config/tmux/tmux.conf
#

# Options ======================================================================

set -g mouse on
set -gq allow-passthrough on
set -g visual-activity off

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename on

# Keybinds =====================================================================

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.config/tmux/tmux.conf

bind v split-window -hc "#{pane_current_path}"
bind s split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind \" split-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind & kill-window
bind x kill-pane

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

bind-key -n 'M-t' new-window
bind-key -n 'M-n' next-window
bind-key -n 'M-N' previous-window
bind-key -n 'M-r' kill-window

bind-key -n 'M-e' split-window -hc "#{pane_current_path}"
bind-key -n 'M-w' split-window -c "#{pane_current_path}"
bind-key -n 'M-q' kill-pane

bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'select-pane -R'

# bind-key -n 'M-H' if-shell "$is_vim" 'send-keys M-H' 'resize-pane -L 5'
# bind-key -n 'M-J' if-shell "$is_vim" 'send-keys M-J' 'resize-pane -D 5'
# bind-key -n 'M-K' if-shell "$is_vim" 'send-keys M-K' 'resize-pane -U 5'
# bind-key -n 'M-L' if-shell "$is_vim" 'send-keys M-L' 'resize-pane -R 5'
bind-key -n 'M-H' resize-pane -L 5
bind-key -n 'M-J' resize-pane -D 5
bind-key -n 'M-K' resize-pane -U 5
bind-key -n 'M-L' resize-pane -R 5

# bind-key -T copy-mode-vi 'M-h' select-pane -L
# bind-key -T copy-mode-vi 'M-j' select-pane -D
# bind-key -T copy-mode-vi 'M-k' select-pane -U
# bind-key -T copy-mode-vi 'M-l' select-pane -R

# Status Bar ===================================================================

set -g focus-events on
set -g status-style fg=#ebdbb2,bg=black

set -g status-right ""
set -g status-left-style fg=#ebdbb2,bold
set -g status-left " [#S] "

setw -g window-status-current-style fg=#ebdbb2,bold
setw -g window-status-current-format "[#W:#I:*]"
setw -g window-status-style fg=#ebdbb2
setw -g window-status-format "[#W:#I]"
